package com.robertconstantindinescu.my_doctor_app.interfaces

import com.robertconstantindinescu.my_doctor_app.models.appointmentModels.PendingPatientAppointmentModel

interface PatientAcceptedAppointmentInterface {
    fun onAcceptedAppointmentClick(patientAppointmentModel: PendingPatientAppointmentModel)
}