package com.robertconstantindinescu.my_doctor_app.interfaces


import com.robertconstantindinescu.my_doctor_app.models.appointmentModels.PendingDoctorAppointmentModel

interface PendingDoctorAppointmentRequestsInterface {
    fun onDoctorPendingAppointmentRequestClick(pendingAppointmentDoctorModel: PendingDoctorAppointmentModel)
    fun onAcceptDoctorPendingAppointmentClick(pendingAppointmentDoctorModel: PendingDoctorAppointmentModel, position:Int)
    fun onCancelDoctorPendingAppointmentClick(pendingAppointmentDoctorModel: PendingDoctorAppointmentModel)


}